name: Pylint

on:
  push:
    branches:
      - "*"

jobs:
  pylint:
    name: Pylint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0
      - name: Install dependencies
        run: |
          pip install pylint pylint-json2html
        shell: bash
      - name: Run pylint
        id: pylint
        run: |
          pylint --rcfile=.pylintrc --output-format=json --score no ./**/*.py> pylint_report.json || true
          pylint_score=$(pylint --rcfile=.pylintrc --score y ./**/*.py || true)
          echo "${pylint_score}"
          score_regex='Your code has been rated at (-?[0-9]+\.[0-9]{2})/10'
          if [[ "${pylint_score}" =~ $score_regex ]]; then
            score="${BASH_REMATCH[1]}"
            echo "score=${score}" >> $GITHUB_OUTPUT
          else
            echo "Unable to extract Pylint score from '${pylint_score}'"
          fi
        shell: bash
      - name: Convert Pylint output to HTML
        run: |
          pylint-json2html -f json -o pylint_report.html pylint_report.json
        shell: bash
      - name: Upload Pylint report as an artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Pylint report
          path: pylint_report.html
      - name: Dynamic Badges
        uses: Schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: f75ffb077874ae17accb0f18037eef5d
          filename: badge.json
          label: Pylint
          message: ${{ steps.pylint.outputs.score }}
          valColorRange: ${{ steps.pylint.outputs.score }}
          maxColorRange: 10
          minColorRange: 8
