name: Pylint

on:
  push:
    branches:
      - "*"

jobs:
  pylint:
    name: Pylint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install pylint pylint-json2html
        shell: bash
      - name: pylint
        run: |
          pylint --output-format=json ./**/*.py --good-names=x,y > pylint_report.json || true
          pylint_score=$(pylint --score y ./**/*.py --good-names=x,y || true)
          echo "SCORE=$pylint_score" >> $GITHUB_ENV
        shell: bash
      - name: Convert Pylint output to HTML
        run: |
          pylint-json2html -f json -o pylint_report.html pylint_report.json
        shell: bash
      - name: Upload Pylint report as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: Pylint report
          path: pylint_report.html
      - name: Dynamic Badges
        uses: Schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: f75ffb077874ae17accb0f18037eef5d
          filename: badge.json
          label: Pylint
          message: ${{ env.SCORE }}
          valColorRange: ${{ env.SCORE }}
          maxColorRange: 10
          minColorRange: 8
